version: 2

networks:
  primary:
    external:
      name: primary

services:
  web:
    image: registry.nush.app/blockly-maze-python:latest
    restart: always
    networks:
    - primary
    expose:
    - "80"
    - "443:443"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.blockly.rule=Host(`blockly.nush.app`)"
    - "traefik.http.routers.blockly.entrypoints=https"
    - "traefik.http.routers.blockly.tls=true"
    - "traefik.http.routers.blockly.tls.certresolver=tlsresolver"
